use_desktop: False
keyboard_switch_map:
    # Enter, Up, Down, Exit
    1: exit
    2: up
    3: down
    4: enter
    8: leftJet
    9: rightJet
    0: bottomJet
    s: startButton
    b: ballLaunch
    d: phantomSwitch
    z: flipperLwL
    /: flipperLwR
    a: leftHandle
    l: rightHandle
    f: rightFreeway
    n: shooterLane
    k: leftOutlane
    r: rightInlane
    p: bottomPopper
    w: leftRampEnter
    e: rightSlingshot
    c: centerRamp
    q: rightRampEnter
    y: chaseCar2
    h: chaseCar1
    m: mtlM
    t: topPopper
    u: leftRampExit
    j: rightRampExit
    x: sideRampExit
    i: elevatorHold
    o: buyIn