Audits: {Avg Ball Time: '0:00', Avg Extra Balls: 0, Avg Game Time: '0:00', Avg Score: 0,
  Balls Played: 0, Games Played: 0, Games Started: 0}
ClassicHighScoreData:
- {date: 'Sun Oct  3 17:38:46 2010', inits: JWL, score: 500000000}
- {date: 'Sun Oct  3 17:44:49 2010', inits: GSS, score: 400000000}
- {date: 'Sun Oct  3 16:22:47 2010', inits: ASP, score: 300000000}
- {date: 'Sun Oct  3 15:04:27 2010', inits: JFP, score: 200000000}
- {date: 'Sun Oct  3 22:05:01 2010', inits: JAP, score: 100000000}
ComboHighScoreData:
- {date: 'Friday Feb  3 13:41:00 2013', inits: JWL, score: 60}
HeadshotHighScoreData:
- {date: 'Friday Feb  3 11:00:00 2013', inits: JWL, score: 20}
PreviousScores: [1000, 0]
